services:
  postgres:
    image: postgres:15-alpine
    container_name: piscicultura_postgres
    environment:
      POSTGRES_DB: ${PG_DBNAME:-piscicultura_history}
      POSTGRES_USER: ${PG_USER:-admin}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  bot_unificado:
    build:
      context: .
      dockerfile: src/bots/Dockerfile
    container_name: peixe_patel_bot
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - postgres
    restart: unless-stopped

# nodered:
#   build:
#     context: ./nodered
#     dockerfile: Dockerfile
#   container_name: piscicultura_nodered
#   ...
