[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
# Carrega as variáveis do .env.test ANTES de tentar carregar .env
# Graças ao plugin pytest-dotenv.
env_files =
    .env.test
testpaths = tests
pythonpath = .
